### ISSUE TITLE
some errors in macOS..

### ISSUE THREAD

**Issue by moebiussurfing** [yumataesu/vanadium#1]
Hey @yumataesu , 
thanks a lot for sharing this.

Sorry for asking, because you said you didn't test on macOS...
Do you think could be easy to solve?

Anyway, how can I update the GLFW as you mention? I looked to the OF GitHub folder I have and seems to be like the included in OF 0.10

I tried to download your ofxGen from the repo but the same errors here.

```
ofxGenManager.h
Warning:(10, 10) non-portable path to file '"ofxGenBaseLayer.h"'; specified path differs in case from file name on disk
Error:(38, 42) non-const lvalue reference to type 'tvec3<...>' cannot bind to a temporary of type 'tvec3<...>'
Error:(39, 44) non-const lvalue reference to type 'tmat4x4<...>' cannot bind to a temporary of type 'tmat4x4<...>'
ofxSSAO.h
Error:(102, 15) extra qualification on member 'genNoiseTexture'
Included from:
(2) /Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/src/main.cpp
(6) src/ofApp.h
```

**Comment by yumataesu** [comment]
Hi, @moebiussurfing 

**1. GLFW update**
 Latest GLFW 3.3 is patched and imgui uses these.
Maybe current oF doesn't contain this version. And I'm using oF 0.10.0 from openFrameworks.cc not from GitHub.  I'm not sure what `download_libs.sh` downloads which version. but replace is easy.

This is how to replace GLFW library.
1. Click & download "GLFW 3.3 Released April 15 2019" from https://www.glfw.org/
2. Build binary of glfw with cmake (I use cmake gui).
3. Replace include file and .lib

So all we have to replace is following files. (In case vs)

* of_v0.10.1/libs/glfw/include/GLFW/glfw3.h
* of_v0.10.1/libs/glfw/include/GLFW/glfw3native.h
* of_v0.10.1/libs/glfw/lib/vs/x64/glfw3.lib




**2.  ofxGen compile error**
 I'll check later on MacOS. It may be because compiler is different from visual studio.
And this application is setted OpenGL 4.5. You have to rewrite some code. for example...

```C++
settings.setGLVersion(4, 5);
```
↓
```C++
settings.setGLVersion(3, 3);
```

**Comment by moebiussurfing** [comment]
Thanks!

**Comment by yumataesu** [comment]
@moebiussurfing 

I've pushed.
Please checkout mac branch and clone recursive submodules.
You can build & run vanadium. It should work.

I have 2 points.

**1. you can't use 3d scene layer.**
Rendering is fine. But compositing is not fine.
Because mac has a gpu limitation in depth_composite shader.
> ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 24 samplers

**2. 2d scene render and composite works fine.**

<img width="1680" alt="ss" src="https://user-images.githubusercontent.com/10915510/70020639-bc044a00-15d0-11ea-972a-7395d57d33af.png">

**Comment by moebiussurfing** [comment]
Cool,
Thanks! I’ll check and report

**Comment by moebiussurfing** [comment]
Thanks a lot for your time! 
it has been hard for my skills...
![Screen Shot 2019-12-03 at 16 10 55](https://user-images.githubusercontent.com/2106149/70081577-9afb2380-15e7-11ea-9034-0a3bfc1a8cd5.png)

I think I made it work... but not sure and I have some errors in console, maybe the ones you mentioned above about shaders limit in macOS.

I tried to compile the glfw-3.3 source, but /of_v0.10.1_osx_release/libs/glfw/lib/osx/glfw3.a hasn't been generated. (added all the folder with default configs and compile)
So I ended downloading the precompiled binaires and renamed the present .a file...:
/glfw-3.3.bin.MACOS/lib-macos/libglfw3.a

**Comment by moebiussurfing** [comment]
```

2019-12-03 15:59:40.158883-0300 vanadiumDebug[21452:130871] MessageTracer: Falling back to default whitelist
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/../../addons/ofxGen/assets/composite/depth_composite.geom"
[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
WARNING: Could not find vertex shader attribute 'normal' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'color' to match BindAttributeLocation request.
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 24 samplers
�
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/../../addons/ofxDeferredLighting/assets/lighting.geom"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/../../addons/ofxSSAO/assets/ssao.geom"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/../../addons/ofxSSAO/assets/ssao.geom"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_VERTEX_SHADER shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer01_2d/render.vert"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_FRAGMENT_SHADER shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer01_2d/render.frag"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer01_2d/render.geom"
[ error ] ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer01_2d/shader.geom"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer03_3d/render.geom"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_VERTEX_SHADER shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer03_2d/render.vert"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_FRAGMENT_SHADER shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer03_2d/render.frag"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer03_2d/render.geom"
[ error ] ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "/Users/manu/Documents/of_v0.10.1_osx_release/apps/TEST/vanadium/bin/data/ofxGen/Layer03_2d/shader.geom"
[warning] Adding another parameter with same name 'Spd' to group 'Layer03_2d'

```
